### ISSUE TITLE
Use row-resize cursor on event hover

### ISSUE THREAD

**Issue by tyler-dane** [SwitchbackTech/compass#117]
**Context**
We're currently showing the minimal `ns-resize` cursor on event hover. This is nice and minimal, but it can be confusing for short events that are 15-minutes long, because it's not clear where exactly the user should click. The `row-resize` cursor allows more granular feedback for the user by providing a horizontal line that makes it more clear where to position the mouse before clicking.

Visuals of all available cursors:
https://developer.mozilla.org/en-US/docs/Web/CSS/cursor

**Tasks**
- [x] change cursor from `ns-resize` to `row-resize`
- [x] use default cursor when resizing 
    - This'll prevent the frequent toggling between default and `ns-resize` cursor, which can be distracting)
- [x] don't swap cursor between `row-resize` and default while resizing
