### ISSUE TITLE
🎨 Update Colors and Typography

### ISSUE THREAD

**Issue by tyler-dane** [SwitchbackTech/compass#152]
## Background
The current colors fail many contrast-ratio tests. Also they're not very cool. Updating the color palette will fix those 2 issue, in addition to making it easier to add more themes in the future. 

## Tasks
- [x] Create themeing strategy
    - ThemeProvider, [styled-components w/ theme,](https://styled-components.com/docs/advanced)
- [x] Colors replace with new
- [x] Colors adhere to WCAG's contract guidelines
- [x] New typography added 

### Colors
- Tiny Color ([library](https://github.com/bgrins/TinyColor))
- Color Contrast Checker ([Chome Extension](https://chromewebstore.google.com/detail/wcag-color-contrast-check/plnahcmalebffmaghcpcmpaciebdhgdf?hl=en&pli=1))
- Color Naming - Semantic Schemas ([Figma talk](https://www.youtube.com/watch?v=1DTnojio89Y&ab_channel=Figma), [StackOverflow Overview](https://stackoverflow.com/questions/50910404/best-practice-for-naming-css-color-variables), [Tailwind Example](https://www.subframe.com/blog/how-to-setup-semantic-tailwind-colors))
 - Color schemes with HSL ([web.dev](https://web.dev/articles/building/a-color-scheme))
- [Tailwind Color Shades](https://javisperez.github.io/tailwindcolorshades)
- [Ayu Colors](https://raw.githubusercontent.com/ayu-theme/ayu-colors/60fdf5d39c5ef36c081b081c1fb90b5e7cc24f4d/colors.svg)

### Fonts
- [Font Sensei](https://fontsensei.com)
